[project]
name = "test-rag"
version = "0.1.0"
description = ""
authors = [
    {name = "TchappiR",email = "tchappiromaric@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "sentence-transformers (>=5.6.0,<6.0.0)",
    "chromadb (>=1.5.9,<2.0.0)",
    "groq (>=1.5.0,<2.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
